name: Start EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  start_ec2_instance:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Start EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0a23a9827c6dab833 \
            --instance-type t2.micro \
            --subnet-id subnet-02d83099e8a7b60c0 \
            --key-name chatbot \
