name: Start EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  start_ec2_instance:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkup environment Variables
        run: echo ${{secrets.aws_access_key_id}}



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-session-token: ${{ secrets.aws_session_token }}
          aws-region: eu-central-1

      - name: Start EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0a23a9827c6dab833 \
            --instance-type t2.micro \
            --subnet-id subnet-02d83099e8a7b60c0 \
            --key-name chatbot \
