name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setze Discord Token
      run: aws secretsmanager get-secret-value --secret-id DISCORD_TOKEN --region eu_central_1 --query SecretString --output text >> discord_token.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: YOUR_REGION

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: chatbottest
        template: cloudformation.yaml
        parameter-overrides: "KeyName=chatbot,DISCORDTOKEN=$(cat discord_token.txt)"
        capabilities: CAPABILITY_IAM
